### ISSUE TITLE
Error while calling str() on response containing datetime object

### ISSUE THREAD

**Issue by ShreyanGupta** [Azure/azure-kusto-python#150]
The __str__ function in class KustoResultTable can not handle datetime objects.

Proposed solution: It would be better to have a default json serializable object in call to json.dumps. This would eliminate the need to have `d["kind"] = d["kind"].value`
```python
    def __str__(self):
        d = self.to_dict()
        return json.dumps(d, default=str)
```
Error trace:
```
Traceback (most recent call last):
  File "util\kusto.py", line 126, in <module>
    cpu = kusto_client.get_compute_cpu_utilization(start_time, end_time, tenant)
  File "util\kusto.py", line 75, in get_compute_cpu_utilization
    results = self._poll_and_execute(query, end_time)
  File "util\kusto.py", line 51, in _poll_and_execute
    logging.info("Polling kusto result {} min: {}".format(i, result))
  File "C:\Users\shregup\AppData\Local\Programs\Python\Python37\lib\site-packages\azure\kusto\data\_models.py", line 170, in __str__
    return json.dumps(d)
  File "C:\Users\shregup\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\shregup\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\shregup\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\shregup\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
```

**Comment by tiagomacarios** [comment]
@danield137 I am also hitting this. Any ETA for a fix?

**Comment by danield137** [comment]
fixing now. sorry for the delay. should be available soon

**Comment by danield137** [comment]
fixed in https://github.com/Azure/azure-kusto-python/releases/tag/v0.0.42
