### ISSUE TITLE
ValueError: Cannot convert non-finite values (NA or inf) to integer

### ISSUE THREAD

**Issue by EricKundan** [Azure/azure-kusto-python#159]
i wanted to map female as 1 and male as 1 in int data type, but getting 'Cannot convert non-finite values (NA or inf) to integer'.i have checked Null value and there is no NaN value in that column.

for dataset in combine:
    dataset['Sex'] = dataset['Sex'].map( {'female': 1, 'male': 0} ).astype(int)

train_df.head()
---------
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-154-eac60ab94fb3> in <module>
      1 for dataset in combine:
----> 2     dataset['Sex']=dataset['Sex'].dropna(axis=0).map({'female':1, 'male':0}).astype(int)
      3 
      4 train.head()

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\generic.py in astype(self, dtype, copy, errors, **kwargs)
   5689             # else, only a single dtype is given
   5690             new_data = self._data.astype(dtype=dtype, copy=copy, errors=errors,
-> 5691                                          **kwargs)
   5692             return self._constructor(new_data).__finalize__(self)
   5693 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\internals\managers.py in astype(self, dtype, **kwargs)
    529 
    530     def astype(self, dtype, **kwargs):
--> 531         return self.apply('astype', dtype=dtype, **kwargs)
    532 
    533     def convert(self, **kwargs):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\internals\managers.py in apply(self, f, axes, filter, do_integrity_check, consolidate, **kwargs)
    393                                             copy=align_copy)
    394 
--> 395             applied = getattr(b, f)(**kwargs)
    396             result_blocks = _extend_blocks(applied, result_blocks)
    397 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\internals\blocks.py in astype(self, dtype, copy, errors, values, **kwargs)
    532     def astype(self, dtype, copy=False, errors='raise', values=None, **kwargs):
    533         return self._astype(dtype, copy=copy, errors=errors, values=values,
--> 534                             **kwargs)
    535 
    536     def _astype(self, dtype, copy=False, errors='raise', values=None,

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\internals\blocks.py in _astype(self, dtype, copy, errors, values, **kwargs)
    631 
    632                     # _astype_nansafe works fine with 1-d only
--> 633                     values = astype_nansafe(values.ravel(), dtype, copy=True)
    634 
    635                 # TODO(extension)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\dtypes\cast.py in astype_nansafe(arr, dtype, copy, skipna)
    674 
    675         if not np.isfinite(arr).all():
--> 676             raise ValueError('Cannot convert non-finite values (NA or inf) to '
    677                              'integer')
    678 

ValueError: Cannot convert non-finite values (NA or inf) to integer

**Comment by ArielYehezkely** [comment]
Hi, 

I'm not sure it's related here, but it could happen if there is a typo or value other than "female" or "male" in the column. 

`fields = ["Sex", "Age"]`
`rows = [["fmale", 23],["male",22],["female",45],["male", 32]]`
`dataset = pandas.DataFrame(data=rows, columns=fields)`
`dataset['Sex'] = dataset['Sex'].map( {'female': 1, 'male': 0} ).astype(int)`

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\Python\Python37\lib\site-packages\pandas\core\generic.py", line 5882, in astype
    dtype=dtype, copy=copy, errors=errors, **kwargs
  File "...\Python\Python37\lib\site-packages\pandas\core\internals\managers.py", line 581, in astype
    return self.apply("astype", dtype=dtype, **kwargs)
  File "...\Python\Python37\lib\site-packages\pandas\core\internals\managers.py", line 438, in apply
    applied = getattr(b, f)(**kwargs)
  File "...\Python\Python37\lib\site-packages\pandas\core\internals\blocks.py", line 559, in astype
    return self._astype(dtype, copy=copy, errors=errors, values=values, **kwargs)
  File "...\Python\Python37\lib\site-packages\pandas\core\internals\blocks.py", line 643, in _astype
    values = astype_nansafe(vals1d, dtype, copy=True, **kwargs)
  File "...\Python\Python37\lib\site-packages\pandas\core\dtypes\cast.py", line 700, in astype_nansafe
    "Cannot convert non-finite values (NA or inf) to " "integer"
ValueError: Cannot convert non-finite values (NA or inf) to integer

**Comment by danield137** [comment]
Closing due to inactivity.
