### ISSUE TITLE
The value for one of the HTTP headers is not in the correct format

### ISSUE THREAD

**Issue by docgregt** [Azure/azure-kusto-python#167]
Hi,
Using following simple code:
```
       KCSB_INGEST = KustoConnectionStringBuilder.with_aad_user_password_authentication(cluster, <u>, <p>)
       ingestclient = KustoIngestClient(KCSB_INGEST)
        dt = []
        for idx, val in enumerate(r,0):
            dt.append([idx, json.dumps(val)])
            
        fields = ['id', 'doc']
        df = pd.DataFrame(data=dt, columns=fields)

        ingestion_props = IngestionProperties(
            database=db_name,
            table=table_name,
            dataFormat=DataFormat.csv,
            )
        ingestclient.ingest_from_dataframe(df, ingestion_properties=ingestion_props)

```
r is just a list of strings.

I always get the following error:
ERROR:azure.storage.common.storageclient:Client-Request-ID=6cfd5cac-d9d2-11e9-a960-70886b83b7da Retry policy did not allow for a retry: Server-Timestamp=Wed, 18 Sep 2019 05:09:00 GMT, Server-Request-ID=7383a49b-e003-0040-7fdf-6d78b3000000, HTTP status code=400, Exception=The value for one of the HTTP headers is not in the correct format.<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidHeaderValue</Code><Message>The value for one of the HTTP headers is not in the correct format.RequestId:7383a49b-e003-0040-7fdf-6d78b3000000Time:2019-09-18T05:09:00.6931679Z</Message><HeaderName>x-ms-version</HeaderName><HeaderValue>2019-02-02</HeaderValue></Error>.
Traceback (most recent call last):
  File "c:\dev\src\i4\Services\i4ServicesPyParsing\KustoCache\__init__.py", line 69, in ingestnoons
    ingestclient.ingest_from_dataframe(df, ingestion_properties=ingestion_props)
  File "c:\dev\src\i4\Services\i4ServicesPyParsing\.env\lib\site-packages\azure\kusto\ingest\_ingest_client.py", line 66, in ingest_from_dataframe
    self.ingest_from_blob(BlobDescriptor(url, fd.size), ingestion_properties=ingestion_properties)
  File "c:\dev\src\i4\Services\i4ServicesPyParsing\.env\lib\site-packages\azure\kusto\ingest\_ingest_client.py", line 121, in ingest_from_blob
    queue_service.put_message(queue_name=queue_details.object_name, content=encoded)
  File "c:\dev\src\i4\Services\i4ServicesPyParsing\.env\lib\site-packages\azure\storage\queue\queueservice.py", line 793, in put_message
    None, None, content])
  File "c:\dev\src\i4\Services\i4ServicesPyParsing\.env\lib\site-packages\azure\storage\common\storageclient.py", line 430, in _perform_request
    raise ex
  File "c:\dev\src\i4\Services\i4ServicesPyParsing\.env\lib\site-packages\azure\storage\common\storageclient.py", line 358, in _perform_request
    raise ex
  File "c:\dev\src\i4\Services\i4ServicesPyParsing\.env\lib\site-packages\azure\storage\common\storageclient.py", line 344, in _perform_request
    HTTPError(response.status, response.message, response.headers, response.body))
  File "c:\dev\src\i4\Services\i4ServicesPyParsing\.env\lib\site-packages\azure\storage\common\_error.py", line 115, in _http_error_handler

I used the following to output to a file to look at the csv and it looks ok to me:
        df.to_csv('foobar', index=False, encoding="utf-8", header=False, compression="gzip")

The database looks like:
![image](https://user-images.githubusercontent.com/43346207/65114037-96d54780-d9a2-11e9-8404-df0259d8f92c.png)

This seems like a permissions issue or like something is missing from setup like a blob storage.
What is missing or why the error?

**Comment by ArielYehezkely** [comment]
Hi, 

Can you please share your `pip freeze` output?
I'm trying to recreate the issue and so far the example code you've provided works for me, so it might be versions issue. 

Thanks, 
Ariel Yehezkely

**Comment by docgregt** [comment]
Hi Ariel,
In working with Prashanth Madi at MS it turns out the issue has to do with setting the user to have the ingest role. Oddly, it seems an admin user does not have ingest role by default and I would suggest updating the tutorials and/or sample code. I also had a problem with the db having dashes in it’s name. Once I fixed both then the issue was resolved so we can close this issue.

Gregory Turner
Chief Architect
________________________________________
i4 Insight, Inc.

cell: +1.720.335.1744
greg.turner@i4-insight.com<mailto:greg.turner@i4-insight.com>

A member of the Lloyd’s Register Group
