### ISSUE TITLE
KustoClient method to execute mgmt async with polling

### ISSUE THREAD

**Issue by alexkyllo** [Azure/azure-kusto-python#223]
**Is your feature request related to a problem? Please describe.**

When I use the client to execute long-running management commands with `execute_mgmt` they often fail with a socket exception and sometimes the POST hangs indefinitely with no response. Long-running HTTP requests are prone to failure. So I prefer to use the `async` operator, but the client provides no built-in functionality for polling the server to check operation status for the operation GUID that's returned.

**Describe the solution you'd like**

I have written some of my own code to submit an async management command and poll the server periodically to check the status of the operation. Would you be interested in a PR to add this functionality to the package?

Quick example:

```python
    def execute_with_polling(self, database, command, poll_wait):
        """Execute an async command and poll the server for result."""
        if not "async" in command:
            msg = "execute_with_polling can only be used with async commands."
            raise ValueError(msg)
        result = self.client.execute_mgmt(database, command)
        op_id = result.primary_results[0].rows[0]['OperationId']
        state = "InProgress"
        should_retry = True
        while state == "InProgress" and should_retry:
            time.sleep(poll_wait)
            op_result = self.client.execute_mgmt(
                database,
                ".show operations {0}".format(op_id)
            )
            state = op_result.primary_results[0].rows[0]['State']
            should_retry = op_result.primary_results[0].rows[0]['ShouldRetry']
            if state == "Failed":
                raise KustoServiceError(op_result.primary_results[0].rows[0]['Status'],
                                        op_result)
            if state == "Completed":
                return op_result
```

**Comment by danield137** [comment]
Hi @alexkyllo, Sorry for the delayed response.
That seems like something that we can definitely do.

Regarding how to, I'm not sure, I will have to give it some thought.

A Few things we need to consider:
1. This is blocking code.
2. Error handling
3. Throttling / Pressure

Just out of curiosity, if you want a sync behaviour, why not drop the `async` keyword?

**Comment by alexkyllo** [comment]
Hi @danield137, Thanks for considering. I had to implement this because I was getting a high failure rate from long-running sync operations, because the server was either closing the connection and  throwing the below exception, or even apparently failing to report this back to the client and leaving the client hanging. If you think there's a better solution to the underlying issue that doesn't require polling, that would be great, but at the moment I am just not experiencing the same reliability from long-running sync commands as I am from async commands.

```
Traceback (most recent call last):
File "[redacted filename]", line 361, in try_execute_async_command
execute_and_poll(client, database, command)
File "[redacted filename]", line 403, in execute_and_poll
raise KustoServiceError(op_result.primary_results[0].rows[0]['Status'],
                                                 azure.kusto.data.exceptions.KustoServiceError: (KustoServiceError(...), "[cluster('[redacted cluster name]')] Partial query failure: 0x80131500 (message: 'Kusto client failed to send a request to the service: The underlying connection was closed: A connection that was expected to be kept alive was closed by the server.. 
Please provide the following information when contacting the Kusto team @ https://aka.ms/kustosupport :
DataSource='https://[redacted cluster name]/v1/rest/querystreaming',
DatabaseName='[redacted db name]',
ClientRequestId='KPC.execute;55d2037c-82ba-43a0-90e5-cfa8816f9c68',
Timestamp='2020-04-16T17:28:20.9124716Z'.  ==> ExecuteInterClusterQuery failure: ', details: 'Source: Kusto.Data\n[0]Kusto.Data.Exceptions.KustoClientException: Kusto client failed to send a request to the service: The underlying connection was closed: A connection that was expected to be kept alive was closed by the server.. 
Please provide the following information when contacting the Kusto team @ https://aka.ms/kustosupport :
DataSource='https://[redacted cluster name]/v1/rest/querystreaming',
DatabaseName='[redacted db name]',
ClientRequestId='KPC.execute;55d2037c-82ba-43a0-90e5-cfa8816f9c68',
Timestamp='2020-04-16T17:28:20.9124716Z'.
Timestamp=2020-04-16T17:28:20.9124716Z
ClientRequestId=KPC.execute;55d2037c-82ba-43a0-90e5-cfa8816f9c68
ActivityId=895689bf-a473-4ad7-90de-12e894afc0b5
ActivityType=DN.RestClient.ExecuteQuery
ServiceAlias=[redacted cluster name]
MachineName=KEngine00000X
ProcessName=Kusto.WinSvc.Svc
ProcessId=8228
ThreadId=10360
AppDomainName=Kusto.WinSvc.Svc.exe
ActivityStack=(Activity stack: CRID=KPC.execute;55d2037c-82ba-43a0-90e5-cfa8816f9c68 ARID=895689bf-a473-4ad7-90de-12e894afc0b5 > DN.FE.ExecuteQuery/5d9044f0-294a-4d3e-998b-d93218b58798 > DN.CrossCluterClient.ExecuteQueryAsKustoDataStream/d69179e0-6da2-4a31-9054-7a7d85ad8f1a > DN.RestClient.ExecuteQuery/8446e165-3dbd-4b13-810d-a3f54698a938)
MonitoredActivityContext=ActivityType=DN.RestClient.ExecuteQuery, Timestamp=2020-04-16T17:28:01.8779701Z, ParentActivityId=d69179e0-6da2-4a31-9054-7a7d85ad8f1a, TimeSinceStarted=19034.5015 [ms]

ErrorMessage=The underlying connection was closed: A connection that was expected to be kept alive was closed by the server.
DataSource=[redacted cluster name]/v1/rest/querystreaming
DatabaseName=[redacted db name]
ClientRequestId=KPC.execute;55d2037c-82ba-43a0-90e5-cfa8816f9c68 --->
System.Net.WebException: The underlying connection was closed: A connection that was expected to be kept alive was closed by the server. ---> System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
   at System.Net.TlsStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Connection.ReadCallback(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
  ([0]Kusto.Data.Exceptions.KustoClientException.StackTrace:)
   at Kusto.Data.Net.Client.RestClient2.<MakeHttpRequestAsyncImpl>d__46.MoveNext() in C:\\source\\Src\\Client\\Kusto.Data\\Net\\RestClient2.cs:line 780
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kusto.Cloud.Platform.Utils.MonitoredActivity.<InvokeAsync>d__12`2.MoveNext() in C:\\source\\Src\\Common\\Kusto.Cloud.Platform\\Utils\\Context\\MonitoredActivity.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Kusto.Cloud.Platform.Utils.MonitoredActivity.<InvokeAsync>d__12`2.MoveNext() in C:\\source\\Src\\Common\\Kusto.Cloud.Platform\\Utils\\Context\\MonitoredActivity.cs:line 236
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kusto.Data.Net.Client.RestClient2.<MakeHttpRequestAsync>d__44.MoveNext() in C:\\source\\Src\\Client\\Kusto.Data\\Net\\RestClient2.cs:line 575
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kusto.Data.Net.Client.RestClient2.<ExecuteQueryAsKustoDataStreamAsync>d__27.MoveNext() in C:\\source\\Src\\Client\\Kusto.Data\\Net\\RestClient2.cs:line 320
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kusto.Data.Net.Client.RestClient2.ExecuteQueryAsKustoDataStream(String hostAddress, String databaseName, String query, ClientRequestProperties properties) in C:\\source\\Src\\Client\\Kusto.Data\\Net\\RestClient2.cs:line 312
   at Kusto.DataNode.Net.InterClusterCommunicationClient.<>c__DisplayClass7_0.<ExecuteQueryAsKustoDataStream>b__0() in C:\\source\\Src\\Engine\\DataNode\\Net\\InterClusterCommunicationClient.cs:line 66
   at Kusto.Cloud.Platform.Utils.MonitoredActivity.Invoke[TActivityType,TResult](TActivityType activityType, Func`1 func, String clientRequestId) in C:\\source\\Src\\Common\\Kusto.Cloud.Platform\\Utils\\Context\\MonitoredActivity.cs:line 154
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Kusto.Cloud.Platform.Utils.MonitoredActivity.Invoke[TActivityType,TResult](TActivityType activityType, Func`1 func, String clientRequestId) in C:\\source\\Src\\Common\\Kusto.Cloud.Platform\\Utils\\Context\\MonitoredActivity.cs:line 163
   at Kusto.DataNode.DataEngineQueryPlan.DataEngineQueryProcessor.DataEngineQueryCallback.ExecuteInterClusterQuery(String clusterFqdn, String database, String queryString, String serializedQueryContextProperties) in C:\\source\\Src\\Engine\\DataNode\\QueryService\\DataEngineQueryPlan\\DataEngineQueryProcessor.cs:line 343'): ")
```

**Comment by danield137** [comment]
A few things that come to mind:
1. That is a nasty error, I'll check if I can do something about that.
2. What are these long running commands if you don't mind me asking? that might be a sign that something isn't working properly (just as well might be valid, just want to make sure).
3. Connection drops make sense for long HTTP calls, you solution makes sense. We can clean it up a bit, but I see no reason why not to do that.

**Comment by alexkyllo** [comment]
Thanks! The commands I'm running are like `.set-or-append async [table_name] <| some_function()` where `some_function` typically runs for around 5 minutes and returns between 250k - 2M rows, once per day, to cache the results of aggregations on a much larger dataset.
