### ISSUE TITLE
Error importing the package in Windows. [Works in Linux]

### ISSUE THREAD

**Issue by sachethegde** [Azure/azure-kusto-python#284]
#### Code Sample, a copy-pastable example if possible
```
pip install azure-kusto-data
pip install azure-kusto-ingest
```

```python
from azure.kusto.data import KustoConnectionStringBuilder
```
#### Problem description

I have installed the pip package in the Windows 10 with Python version 3.7
I ran into errors while importing the package.

#### Error 
```
>>> from azure.kusto.data import KustoConnectionStringBuilder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\sahegd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\azure\kusto\data\__init__.py", line 5, in <module>
    from .client import KustoClient, KustoConnectionStringBuilder, ClientRequestProperties
  File "C:\Users\sahegd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\azure\kusto\data\client.py", line 18, in <module>
    from .security import _AadHelper
  File "C:\Users\sahegd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\azure\kusto\data\security.py", line 12, in <module>
    from azure.identity import ManagedIdentityCredential
  File "C:\Users\sahegd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\azure\identity\__init__.py", line 9, in <module>
    from ._credentials import (
  File "C:\Users\sahegd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\azure\identity\_credentials\__init__.py", line 5, in <module>
    from .authorization_code import AuthorizationCodeCredential
  File "C:\Users\sahegd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\azure\identity\_credentials\authorization_code.py", line 8, in <module>
    from .._internal.aad_client import AadClient
  File "C:\Users\sahegd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\azure\identity\_internal\__init__.py", line 50, in <module>
    from .certificate_credential_base import CertificateCredentialBase
  File "C:\Users\sahegd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\azure\identity\_internal\certificate_credential_base.py", line 11, in <module>
    from .persistent_cache import load_service_principal_cache
  File "C:\Users\sahegd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\azure\identity\_internal\persistent_cache.py", line 9, in <module>
    import msal_extensions
  File "C:\Users\sahegd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\msal_extensions\__init__.py", line 12, in <module>
    from .cache_lock import CrossPlatLock
  File "C:\Users\sahegd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\msal_extensions\cache_lock.py", line 5, in <module>
    import portalocker
  File "C:\Users\sahegd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\portalocker\__init__.py", line 4, in <module>
    from . import portalocker
  File "C:\Users\sahegd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\portalocker\portalocker.py", line 9, in <module>
    import win32file
ImportError: DLL load failed: The specified module could not be found.
```

#### Output of ``pip freeze`` 

<details>

PS C:\Users\sahegd> pip freeze
adal==1.2.5
appdirs==1.4.3
azure-core==1.9.0
azure-identity==1.5.0
azure-kusto-data==1.0.3
azure-kusto-ingest==1.0.3
azure-storage-blob==12.6.0
azure-storage-queue==12.1.4
backcall==0.1.0
certifi==2020.11.8
cffi==1.14.4
chardet==3.0.4
colorama==0.4.1
cryptography==3.2.1
decorator==4.4.0
distlib==0.3.0
filelock==3.0.12
idna==2.10
importlib-metadata==1.5.0
ipython==7.8.0
ipython-genutils==0.2.0
isodate==0.6.0
jedi==0.15.1
jupyter-client==5.3.1
jupyter-core==4.5.0
msal==1.6.0
msal-extensions==0.3.0
msrest==0.6.19
oauthlib==3.1.0
parso==0.5.1
pexpect==4.8.0
pickleshare==0.7.5
portalocker==1.7.1
powershell-kernel==0.0.8
prompt-toolkit==2.0.9
ptyprocess==0.6.0
pycparser==2.20
Pygments==2.4.2
PyJWT==1.7.1
python-dateutil==2.8.0
pywin32==300
pyzmq==18.1.0
requests==2.25.0
requests-oauthlib==1.3.0
six==1.12.0
tornado==6.0.3
traitlets==4.3.2
urllib3==1.26.2
virtualenv==20.0.7
wcwidth==0.1.7
zipp==3.0.0
</details>

**Comment by ArielYehezkely** [comment]
Hi @sachethegde, 

Thanks for reporting, this is not an issue of this package but an [issue of pywin32](https://github.com/mhammond/pywin32/issues/1634) we consume through azure-identity. 
It will be fixed once pywin32 will release a new version, meantime, can you please downgrade manually the pywin32 package to version 228? 

Thanks, 
Ariel Yehezkely
