### ISSUE TITLE
ImportError: cannot import name 'NoReturn' 

### ISSUE THREAD

**Issue by ishaniparikh** [Azure/azure-kusto-python#340]
#### Code Sample, a copy-pastable example if possible

```
from azure.kusto.data.helpers import dataframe_from_result_table

```
#### Problem description
Traceback (most recent call last):
  File "TestFile.py", line 15, in <module>
    from azure.kusto.data.helpers import dataframe_from_result_table
  File "/usr/bin/anaconda/envs/py35test/lib/python3.5/site-packages/azure/kusto/data/__init__.py", line 5, in <module>
    from .client import KustoClient, KustoConnectionStringBuilder, ClientRequestProperties
  File "/usr/bin/anaconda/envs/py35test/lib/python3.5/site-packages/azure/kusto/data/client.py", line 11, in <module>
    from typing import TYPE_CHECKING, Union, Callable, Optional, Any, NoReturn, Coroutine
ImportError: cannot import name 'NoReturn'

Any resolution or workaround available here for this issue?

**Comment by AsafMah** [comment]
What python version are you on?

**Comment by yogilad** [comment]
@AsafMah , let's comment this type out with note to uncomment once we remove support for python 3.5.
