### ISSUE TITLE
Aio modules not installed, run 'pip install azure-kusto-data[aio]' to leverage aio capabilities

### ISSUE THREAD

**Issue by sky94520** [Azure/azure-kusto-python#386]
Hi, I try using async to query data from ADX, but when I run my code, the error is:
```
Traceback (most recent call last):
  File "/Users/xx/PycharmProjects/dlt/venv/lib/python3.8/site-packages/azure/kusto/data/security.py", line 76, in acquire_authorization_header_async
    return _get_header_from_dict(await self.token_provider.get_token_async())
  File "/Users/xx/PycharmProjects/dlt/venv/lib/python3.8/site-packages/azure/kusto/data/_token_providers.py", line 146, in get_token_async
    await self._init_once_async()
  File "/Users/xx/PycharmProjects/dlt/venv/lib/python3.8/site-packages/azure/kusto/data/_token_providers.py", line 102, in _init_once_async
    await (sync_to_async(self._init_resources)())
  File "/Users/xx/PycharmProjects/dltvenv/lib/python3.8/site-packages/azure/kusto/data/_token_providers.py", line 22, in sync_to_async
    raise KustoAioSyntaxError()
azure.kusto.data.exceptions.KustoAioSyntaxError: Aio modules not installed, run 'pip install azure-kusto-data[aio]' to leverage aio capabilities
```

but I don't found the package: azure-kusto-data[aio]
Could you please tell me how to install the package?

Regards.

**Comment by sky94520** [comment]
I found should install package:
asgiref==3.5.0
