### ISSUE TITLE
BadRequest_SyntaxError when running create table command

### ISSUE THREAD

**Issue by schacki** [Azure/azure-kusto-python#473]
#### Code Sample

```python
KUSTO_DATABASE = 'DbJsErc'
REGION = "northeurope"
CLUSTER_NAME = 'kvc0rqpapuw5sdsq51c0sa'
KUSTO_INGEST_URI = f"https://ingest-{CLUSTER_NAME}.{REGION}.kusto.windows.net/"
CREATE_TABLE_COMMAND = ".create table test (test: string)"

kcsb_ingest = KustoConnectionStringBuilder.with_interactive_login(KUSTO_INGEST_URI)
client_ingest = KustoClient(kcsb_ingest)
client_ingest.execute_mgmt(KUSTO_DATABASE, CREATE_TABLE_COMMAND)
```

#### When running above code on Windows 10, Python 3.6, after the the login screen prompt, I get the following error:

```python
Traceback (most recent call last):
  File "C:\Users\js\Documents\Workspace\erc\venv\lib\site-packages\azure\kusto\data\client.py", line 308, in _execute
    response.raise_for_status()
  File "C:\Users\js\Documents\Workspace\erc\venv\lib\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: BadRequest for url: https://ingest-kvc0rqpapuw5sdsq51c0sa.northeurope.kusto.windows.net/v1/rest/mgmt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".\main.py", line 42, in <module>
    client_ingest.execute_mgmt(KUSTO_DATABASE, CREATE_TABLE_COMMAND)
  File "C:\Users\js\Documents\Workspace\erc\venv\lib\site-packages\azure\core\tracing\decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "C:\Users\js\Documents\Workspace\erc\venv\lib\site-packages\azure\kusto\data\client.py", line 190, in execute_mgmt
    return self._execute(self._mgmt_endpoint, database, query, None, self._mgmt_default_timeout, properties)
  File "C:\Users\js\Documents\Workspace\erc\venv\lib\site-packages\azure\kusto\data\client.py", line 310, in _execute
    raise self._handle_http_error(e, endpoint, payload, response, response.status_code, response_json, response.text)
  File "C:\Users\js\Documents\Workspace\erc\venv\lib\site-packages\azure\kusto\data\client_base.py", line 113, in _handle_http_error
    raise KustoApiError(response_json, http_response=response) from exception
azure.kusto.data.exceptions.KustoApiError: Syntax error: {
    "error": {
        "code": "BadRequest_SyntaxError",
        "message": "Request is invalid and cannot be executed.",
        "@type": "Kusto.Data.Exceptions.SyntaxException",
        "@message": "Syntax error: ",
        "@context": {
            "timestamp": "2023-04-27T09:14:21.7943332Z",
            "serviceAlias": "INGEST-KVCHOSTEREUROPA2.KVC0RQPAPUW5SDSQ51C0SA",
            "machineName": "KDataMana00000B",
            "processName": "Kusto.DM.Svc",
            "processId": 11076,
            "threadId": 13084,
            "clientRequestId": "KPC.execute;284a4f47-6d89-428a-98ad-ff0a0d8d8792",
            "activityId": "96034152-33a2-446d-ac0f-117a5a858e3d",
            "subActivityId": "5da5c183-c173-433f-8803-789c35f03879",
            "activityType": "DN.Admin.Client.ExecuteControlCommand",
            "parentActivityId": "b775b429-81e3-4433-b1a5-62339e3fa58e",
            "activityStack": "(Activity stack: CRID=KPC.execute;284a4f47-6d89-428a-98ad-ff0a0d8d8792 ARID=96034152-33a2-446d-ac0f-117a5a858e3d > GW.Http.CallContext/96034152-33a2-446d-ac0f-117a5a858e3d > GW.ExecuteQuery/b775b429-81e3-4433-b1a5-62339e3fa58e > DN.Admin.Client.ExecuteControlCommand/5da5c183-c173-433f-8803-789c35f03879)"
        },
        "@permanent": true
    }
}
```

#### Output of ``pip freeze`` 

azure-core==1.24.2
azure-identity==1.10.0
azure-kusto-data==4.1.4
azure-kusto-ingest==4.1.4
azure-storage-blob==12.13.1
azure-storage-queue==12.4.0
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==2.0.12
cryptography==40.0.2
dataclasses==0.8
idna==3.4
ijson==3.2.0.post0
isodate==0.6.1
msal==1.22.0
msal-extensions==1.0.0
msrest==0.7.1
oauthlib==3.2.2
portalocker==2.7.0
pycparser==2.21
PyJWT==2.4.0
python-dateutil==2.8.2
pywin32==305
requests==2.27.1
requests-oauthlib==1.3.1
six==1.16.0
tenacity==8.2.2
typing_extensions==4.1.1
urllib3==1.26.15

**Comment by AsafMah** [comment]
You are using the ingest uri (https://ingest-).
This interface is for ingesting (as well as some control commands related to ingestion)
You want to connect to the query/engine endpoint - without the "ingest-" at the start

**Comment by yogilad** [comment]
According to the error your code change did not take affect 
"requests.exceptions.HTTPError: 400 Client Error: BadRequest for url: https://ingest-kvc0rqpapuw5sdsq51c0sa.northeurope.kusto.windows.net/v1/rest/mgmt"

Can you try again?

**Comment by yogilad** [comment]
@schacki , did you manage to resolve the issue, or do you still need assistance?

**Comment by schacki** [comment]
I still have the issue.

**Comment by AsafMah** [comment]
Ok - let's be 100% sure
print all of the variables after every line, and send us the results

**Comment by yogilad** [comment]
@schacki , can you share the information Asaf requested?

**Comment by AsafMah** [comment]
Closing as no information was provided.
Feel free to comment with updated information.
