### ISSUE TITLE
Having trouble autheticating with azure cli

### ISSUE THREAD

**Issue by albecker1** [Azure/azure-kusto-python#480]
#### Code Sample, a copy-pastable example if possible

```python
from azure.kusto.data import KustoClient, KustoConnectionStringBuilder, ClientRequestProperties
from azure.kusto.data.exceptions import KustoServiceError
import time
from datetime import datetime
from datetime import timedelta

cluster = "https://cluster.location..kusto.windows.net"
database = "database"
query = "table" \
           "| take 10"

kcsb = KustoConnectionStringBuilder.with_az_cli_authentication(connection_string=cluster)
client = KustoClient(kcsb)
properties = ClientRequestProperties()
properties.set_option(properties.request_timeout_option_name, timedelta(seconds=1200))

try:
    response = client.execute(database, query, properties)
    # Process the response...
except KustoServiceError as ex:
    print("Kusto service error:", ex)

```
#### Problem description

I am having trouble authenticating with using the cli authentication on Azure Kusto Data and I am not sure why. Above is the code I have written but it fails in one of the libraries for security and authentication when I actually go to execute the query. Here is the traceback call from the console:

Traceback (most recent call last):
  File "C:\Users\albecker\Documents\KustoPythonExperiments\testAuthetication.py", line 20, in <module>
    response = client.execute(database, query, properties)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\albecker\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\azure\kusto\data\client.py", line 556, in execute
    return self.execute_query(database, query, properties)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\albecker\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\azure\kusto\data\client.py", line 568, in execute_query
    return self._execute(self._query_endpoint, database, query, None, KustoClient._query_default_timeout, properties)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\albecker\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\azure\kusto\data\client.py", line 639, in _execute
    request_headers["Authorization"] = self._auth_provider.acquire_authorization_header()
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\albecker\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\azure\kusto\data\security.py", line 132, in acquire_authorization_header
    return self._acquire_authorization_header()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\albecker\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\azure\kusto\data\security.py", line 193, in _acquire_authorization_header
    self.auth_context = AuthenticationContext(self.authority_uri)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\albecker\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\adal\authentication_context.py", line 88, in __init__
    self.authority = Authority(authority, validate_authority is None or validate_authority)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\albecker\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\adal\authority.py", line 49, in __init__
    self._validate_authority_url()
  File "C:\Users\albecker\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\adal\authority.py", line 73, in _validate_authority_url
    raise ValueError("The authority url must be an https endpoint.")
ValueError: The authority url must be an https endpoint.

When I go to debug the authority URL, it is blank and I am not sure where I would need to get that information or input it. Is the Authority URL the cluster URL? If so, it doesn't appear to be passed along.

#### If query related, does it happen on other platforms (Kusto Web UI, Kusto Explorer)? 

Not query related, queries run on kusto explorer

#### Output of ``pip freeze`` 

<details>
adal==1.2.7
applicationinsights==0.11.10
argcomplete==2.1.2
azure-cli-core==2.49.0
azure-cli-telemetry==1.0.8
azure-core==1.26.4
azure-identity==1.13.0
azure-kusto-data==4.2.0
azure-kusto-data-bot==0.1.4
azure-kusto-ingest==4.2.0
azure-mgmt-core==1.4.0
azure-storage-blob==12.16.0
azure-storage-queue==12.6.0
bcrypt==4.0.1
certifi==2023.5.7
cffi==1.15.1
charset-normalizer==3.1.0
cryptography==40.0.2
humanfriendly==10.0
idna==3.4
ijson==3.2.0.post0
isodate==0.6.1
jmespath==1.0.1
knack==0.10.1
msal==1.20.0
msal-extensions==1.0.0
msrest==0.7.1
msrestazure==0.6.4
oauthlib==3.2.2
packaging==23.1
paramiko==3.2.0
pkginfo==1.9.6
portalocker==2.7.0
psutil==5.9.5
pycparser==2.21
Pygments==2.15.1
PyJWT==2.7.0
pymsalruntime==0.13.9
PyNaCl==1.5.0
pyOpenSSL==23.1.1
pyreadline3==3.4.1
PySocks==1.7.1
python-dateutil==2.8.2
pywin32==306
PyYAML==6.0
requests==2.31.0
requests-oauthlib==1.3.1
six==1.16.0
tabulate==0.9.0
tenacity==8.2.2
typing_extensions==4.6.0
urllib3==2.0.2

</details>

**Comment by albecker1** [comment]
Uninstalled Library and dependencies and reinstalled fixed this issue.
